pageinfo = [[1222379969,2253],
	[1222380025,2337],
	[1222375907,7384],
	[1222380087,2399],
	[1222376513,2411],
	[1222373475,2039],
	[1222358299,2015],
	[1222373705,4517],
	[1222358187,2012],
	[1222369609,2628],
	[1222358223,2025],
	[1222338859,2037],
	[1222358203,2050],
	[1222358115,2021],
	[1222369595,2705],
	[1222379949,2943],
	[1222373511,2022],
	[1222381425,4605],
	[1222373491,2034],
	[1222373531,1987],
	[1222381561,3682],
	[1222380093,5157],
	[1222381503,2530],
	[1222377745,7322],
	[1222379731,2559]];
pagedata = [ ["./chapter_2.htm","Przewodnik po funkcjach","﻿Przewodnik po funkcjach Top Previous Next W kolejnych podrozdziałach opisane zostanie szczegółowo korzystanie z oprogramowania w zależności od up...",""],
["./dane.htm","Dane","﻿Dane Top Previous Next Zakładka \"DANE\" daje pracownikowi możliwość wglądu do własnych danych szczegółowych. Nie ma on jednak możliwości modyfikac...",""],
["./funkcja1.htm","Pracownik","﻿Pracownik Top Previous Next W tej zakładce istnieje możliwość przeglądania danych pracownika oraz dokonywania związanych z nim modyfikacji takich...",""],
["./harmonogram.htm","Harmonogram","﻿Harmonogram Top Previous Next Przeglądanie harmonogramu pracy na bieżący miesiąć oraz wszystkich harmonogramów wstecz. Po kliknięciu na przycisk ...",""],
["./harmonogram2.htm","Harmonogram","﻿Harmonogram Top Previous Next Podgląd harmonogramu na bieżący miesiąć dla wybranego pracownika. Aby dodać harmonogram na kolejny miesiąc wybieram...",""],
["./harmonogramy.htm","Harmonogramy","﻿Harmonogramy Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Soft...",""],
["./introduction.htm","Wprowadzenie","﻿Wprowadzenie Top Next Korzystanie z oprogramowania EyeOfBoss. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169;...",""],
["./kadrowy.htm","Okno kadrowego","﻿Okno kadrowego Top Previous Next Ta funkcja daje bardzo duże możliwości jeśli chodzi o komunikację z bazą danych. Kadrowy to najbardziej odpowied...",""],
["./new.htm","New","﻿New Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Software. All...",""],
["./new2.htm","Rejestracja","﻿Rejestracja Top Previous Next W tej zakładce pracownik ma 2 możliwości: rozpoczęcie dnia pracy oraz zakończenie dnia pracy. Jest to podstawowa or...",""],
["./new3.htm","new","﻿new Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Software. All...",""],
["./new_topic.htm","New topic","﻿New topic Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Softwar...",""],
["./okno_administratora.htm","Okno administratora","﻿Okno administratora Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; ...",""],
["./okno_szefa.htm","Okno szefa","﻿Okno szefa Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Softwa...",""],
["./pracownik.htm","Okno pracownika","﻿Okno pracownika Top Previous Next Pracownik jest najczęstszym użytkownikiem oprogramowania EyeOfBoss, a jednocześnie posiada najmniejsze uprawnie...",""],
["./second_topic.htm","Możliwości programu","﻿Możliwości programu Top Previous Next EyeOfBoss daje następujące możliwości: - Indywidualne logowanie każdego z pracowników z możliwością rozpocz...",""],
["./sprzet.htm","Sprzęt","﻿Sprzęt Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Software. ...",""],
["./sprzet2.htm","Sprzęt","﻿Sprzęt Top Previous Next Za pomocą zakładki sprzęt możemy: • Wyświetlić cały wolny sprzęt - wybranie pola \"WOLNY\" • Wyświetlić sprzęt przydzielon...",""],
["./statystyka.htm","Statystyka","﻿Statystyka Top Previous Next Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Softwa...",""],
["./stawki.htm","Stawka","﻿Stawka Top Previous Enter topic text here. This help file was created with an unregistered evaluation copy of Help &#38; Manual. &#169; EC Software. All r...",""],
["./sub_chapter_2_1.htm","Logowanie","﻿Logowanie Top Previous Next Po uruchomieniu programu EyeOfBoss ukazuje się ekran logowania: Za pomocą rozwijalnego menu możemy wybrać rodzaj funk...",""],
["./urlop.htm","Urlop","﻿Urlop Top Previous Next Pracownik może przeglądać wszystkie zwolnienia i urlopy na jakich był w bieżącym roku. W tabelce widnieją również urlopy ...",""],
["./welcome_topic.htm","Czym jest EyeOfBoss?","﻿Czym jest EyeOfBoss? Top Previous Next EyeofBoss to oprogramowanie stworzone głównie z myślą o średnich oraz dużych firmach, w których spora licz...",""],
["./wyplata.htm","Wypłata","﻿Wypłata Top Previous Next Zatwierdzanie stawki oraz wypłaty dla wybranego pracownika. Wybór stawki 1. Z listy rozwijalnej wybieramy jedną z dostę...",""],
["./zwolnienia.htm","Zwolnienia","﻿Zwolnienia Top Previous Next Przeglądanie zwolnień oraz urlopów pracownika w wybranym roku. Zatwierdzanie bądź odrzucanie wniosków o urlop. Aby z...",""]];
